# Generated by Django 3.1.7 on 2021-03-01 20:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='prix')),
                ('tva', models.DecimalField(choices=[(None, 'Taux TVA'), (Decimal('0.05'), '5,5 %'), (Decimal('0.2'), '20 %')], decimal_places=2, max_digits=3, verbose_name='tva')),
                ('stock_available', models.PositiveIntegerField(verbose_name='stock disponible')),
                ('stock_ordered', models.PositiveIntegerField(verbose_name='stock commandé')),
            ],
        ),
    ]
