# Generated by Django 3.1.7 on 2021-03-02 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210302_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tva',
            field=models.DecimalField(choices=[(Decimal('0.055'), '5,5 %'), (Decimal('0.2'), '20 %')], decimal_places=2, max_digits=4, verbose_name='tva'),
        ),
    ]
